version: '3.4'

services:
  naming-server:
    image: jacksoncalixto/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - calixto-network
  zipkin:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    networks:
      - calixto-network
networks:
  calixto-network:
    driver: bridge